### Create index customers
PUT http://localhost:9200/customers

### Create index products
PUT http://localhost:9200/products

### Create index orders
PUT http://localhost:9200/orders

### Show all indices
GET http://localhost:9200/_cat/indices?v


### Delete index customers
DELETE http://localhost:9200/customers

### Delete index products
DELETE http://localhost:9200/products

### Delete index orders
DELETE http://localhost:9200/orders

### Show all indices
GET http://localhost:9200/_cat/indices?v

