### Update mapping customers_v2
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
    "properties": {
        "address": {
            "properties": {
                "street": {
                    "type": "text"
                },
                "city": {
                    "type": "text"
                },
                "province": {
                    "type": "text"
                },
                "country": {
                    "type": "text"
                },
                "zip_code": {
                    "type": "keyword"
                }
            }
        }
    }
}

### Get mapping customers_v2
GET http://localhost:9200/customers_v2/_mapping

### Insert bulk custimer
POST http://localhost:9200/_bulk
Content-Type: application/json

< data/customers-with-addresses.json

### Search customer
POST http://localhost:9200/customer/_search