### Update mapping customers_v2
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
    "properties": {
        "hobbies": {
            "type": "text"
        },
        "banks": {
            "properties": {
                "name": {
                    "type": "text"
                },
                "account_number": {
                    "type": "keyword"
                }
            }
        }
    }
}

### Get mapping customers_v2
GET http://localhost:9200/customers_v2/_mapping

### Bulk insert customer
POST http://localhost:9200/_bulk
Content-Type: application/json

< data/customers-with-banks-and-hobbies.json

### Search customer
POST http://localhost:9200/customer/_search
