# melihat score yg dihitung dr query yg dikirim

### explain score customer username126
POST http://localhost:9200/customer/_explain/username126
Content-Type: application/json

{
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "hobbies": "gaming"
                    }
                }
            ],
            "should": [
                {
                    "term": {
                        "banks.name": "bca"
                    }
                },
                {
                    "term": {
                        "banks.name": "bni"
                    }
                }
            ],
            "minimum_should_match": 1
        }
    }
}